# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.3’

target 'UVa Dining App' do
  	use_frameworks!
	pod 'Alamofire', '~> 4.0'
	pod "SwiftSoup"
	pod 'KeychainSwift', '~> 10.0'
end
